//! The macOS **`LaunchAgent`**: a per-user agent, no administrator involved.
//!
//! An agent lives in the user's own `~/Library/LaunchAgents`, is loaded in
//! their login session and runs as them. A `LaunchDaemon` would run system-wide
//! and need `sudo` — for a service whose entire job is to read one person's
//! files, that is a privilege nobody should have to grant.

use super::quote::xml_text;
use super::spec::{SERVICE_DESCRIPTION, SERVICE_LABEL, ServiceSpec};

/// The file name of the generated agent.
pub(crate) const PLIST_FILE: &str = "com.bookmarksbutbetter.bbb.plist";

/// Renders the `LaunchAgent` property list for `spec`.
///
/// `KeepAlive` is the dictionary form rather than `true`: a bare `true` would
/// restart the daemon after a deliberate stop, whereas `SuccessfulExit=false`
/// means "restart it only when it failed", which is the same intent as
/// systemd's `Restart=on-failure`.
pub(crate) fn plist(spec: &ServiceSpec) -> String {
    use core::fmt::Write as _;

    let mut arguments = String::new();
    for argument in &spec.command_line() {
        let _ = writeln!(arguments, "\t\t<string>{}</string>", xml_text(argument));
    }

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <!-- {SERVICE_DESCRIPTION}. Generated by `bbb service install`; edits are replaced on the next install. -->\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \t<key>Label</key>\n\
         \t<string>{SERVICE_LABEL}</string>\n\
         \t<key>ProgramArguments</key>\n\
         \t<array>\n{arguments}\t</array>\n\
         \t<key>RunAtLoad</key>\n\
         \t<true/>\n\
         \t<key>KeepAlive</key>\n\
         \t<dict>\n\
         \t\t<key>SuccessfulExit</key>\n\
         \t\t<false/>\n\
         \t</dict>\n\
         \t<key>ProcessType</key>\n\
         \t<string>Background</string>\n\
         \t<key>EnvironmentVariables</key>\n\
         \t<dict>\n\
         \t\t<key>BBB_LOG</key>\n\
         \t\t<string>info</string>\n\
         \t</dict>\n\
         </dict>\n\
         </plist>\n"
    )
}

/// Recovers the command line from `ProgramArguments`.
pub(crate) fn command_line(plist: &str) -> Option<Vec<String>> {
    let after_key = plist.split_once("<key>ProgramArguments</key>")?.1;
    let array = after_key.split_once("<array>")?.1;
    let array = array.split_once("</array>")?.0;

    let mut arguments = Vec::new();
    let mut rest = array;
    while let Some((_, tail)) = rest.split_once("<string>") {
        let (value, tail) = tail.split_once("</string>")?;
        arguments.push(unescape_xml(value));
        rest = tail;
    }
    (!arguments.is_empty()).then_some(arguments)
}

fn unescape_xml(value: &str) -> String {
    value
        // `&amp;` last: undoing it first would let `&amp;lt;` become `<`.
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

#[cfg(test)]
mod tests {
    use super::super::spec::{port_in, vault_in};
    use super::*;
    use std::path::PathBuf;

    const AWKWARD: &[&str] = &[
        "/Users/user/Vault",
        "/Users/user/My Bookmarks",
        "/Users/user/Zakładki",
        "/Users/user/书签 📚",
        "/Users/user/a&b",
        "/Users/user/<tag>",
        "/Users/user/say \"hi\"",
        "/Users/user/it's mine",
        "/Users/user/100% done",
    ];

    #[test]
    fn a_generated_agent_round_trips_every_awkward_path() {
        for vault in AWKWARD {
            let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", vault)
                .with_port(47321)
                .expect("valid port");
            let text = plist(&spec);
            let parsed = command_line(&text).expect("ProgramArguments");

            assert_eq!(parsed, spec.command_line(), "round trip for {vault}");
            assert_eq!(vault_in(&parsed), Some(PathBuf::from(vault)));
            assert_eq!(port_in(&parsed), Some(47321));
        }
    }

    #[test]
    fn markup_in_a_path_cannot_break_out_of_its_element() {
        let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", "/Users/user/</string><key>evil");
        let text = plist(&spec);

        // The escaped form is what is written...
        assert!(text.contains("&lt;/string&gt;"), "{text}");
        // ...and the array still has exactly the arguments it should.
        let parsed = command_line(&text).expect("ProgramArguments");
        assert_eq!(parsed, spec.command_line());
    }

    #[test]
    fn the_agent_restarts_only_after_a_failure_and_runs_in_the_background() {
        let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", "/Users/user/Vault");
        let text = plist(&spec);

        assert!(text.contains("<key>SuccessfulExit</key>"), "{text}");
        assert!(text.contains("<key>RunAtLoad</key>"), "{text}");
        assert!(text.contains("<string>Background</string>"), "{text}");
        assert!(text.contains(SERVICE_LABEL), "{text}");
    }

    #[test]
    fn a_plist_without_program_arguments_yields_nothing() {
        assert_eq!(command_line("<plist><dict></dict></plist>"), None);
    }
}
