//! The Windows **Scheduled Task**, triggered at logon.
//!
//! A Windows service proper requires administrator rights and a service
//! control handler; a scheduled task with a logon trigger needs neither, runs
//! as the user, and can restart on failure. For a daemon that serves one
//! person's files on loopback, the task is the right shape.
//!
//! `schtasks /Create /XML` reads the definition from a file that must be
//! UTF-16 — it rejects UTF-8 with a misleading parse error — which is why
//! [`utf16le_bytes`] exists rather than the caller writing the string directly.

use super::quote::{windows_argument, xml_text};
use super::spec::{SERVICE_DESCRIPTION, ServiceSpec};

/// The task name registered with the scheduler.
/// Re-exported for the Windows integration that will register it.
pub const TASK_NAME: &str = "Bookmarks But Better\\bbb";

/// The file name of the generated definition.
pub(crate) const TASK_FILE: &str = "bbb-task.xml";

/// Renders the Task Scheduler XML for `spec`.
///
/// `<Enabled>` on the trigger, `IgnoreNew` for a second start, and a
/// `RestartOnFailure` policy together give roughly what `Restart=on-failure`
/// gives on Linux. Battery settings are turned off because a laptop on battery
/// is exactly when someone opens a browser.
pub(crate) fn task(spec: &ServiceSpec) -> String {
    let command = xml_text(&spec.exe.to_string_lossy());
    let arguments = xml_text(
        &spec
            .arguments()
            .iter()
            .map(|argument| windows_argument(argument))
            .collect::<Vec<_>>()
            .join(" "),
    );

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n\
         <!-- Generated by `bbb service install`. Edits are replaced on the next install. -->\n\
         <Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n\
         \t<RegistrationInfo>\n\
         \t\t<Description>{SERVICE_DESCRIPTION}</Description>\n\
         \t</RegistrationInfo>\n\
         \t<Triggers>\n\
         \t\t<LogonTrigger>\n\
         \t\t\t<Enabled>true</Enabled>\n\
         \t\t</LogonTrigger>\n\
         \t</Triggers>\n\
         \t<Principals>\n\
         \t\t<Principal id=\"Author\">\n\
         \t\t\t<LogonType>InteractiveToken</LogonType>\n\
         \t\t\t<RunLevel>LeastPrivilege</RunLevel>\n\
         \t\t</Principal>\n\
         \t</Principals>\n\
         \t<Settings>\n\
         \t\t<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n\
         \t\t<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n\
         \t\t<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n\
         \t\t<StartWhenAvailable>true</StartWhenAvailable>\n\
         \t\t<ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n\
         \t\t<RestartOnFailure>\n\
         \t\t\t<Interval>PT1M</Interval>\n\
         \t\t\t<Count>3</Count>\n\
         \t\t</RestartOnFailure>\n\
         \t</Settings>\n\
         \t<Actions Context=\"Author\">\n\
         \t\t<Exec>\n\
         \t\t\t<Command>{command}</Command>\n\
         \t\t\t<Arguments>{arguments}</Arguments>\n\
         \t\t</Exec>\n\
         \t</Actions>\n\
         </Task>\n"
    )
}

/// Encodes the definition as the UTF-16LE-with-BOM bytes `schtasks` requires.
pub(crate) fn utf16le_bytes(xml: &str) -> Vec<u8> {
    let mut bytes = vec![0xFF, 0xFE];
    for unit in xml.encode_utf16() {
        bytes.extend_from_slice(&unit.to_le_bytes());
    }
    bytes
}

/// Recovers the command line — executable first — from a task definition.
pub(crate) fn command_line(task: &str) -> Option<Vec<String>> {
    let command = element(task, "Command")?;
    let arguments = element(task, "Arguments").unwrap_or_default();

    let mut line = vec![command];
    line.extend(split(&arguments));
    Some(line)
}

fn element(xml: &str, name: &str) -> Option<String> {
    let open = format!("<{name}>");
    let close = format!("</{name}>");
    let after = xml.split_once(&open)?.1;
    let value = after.split_once(&close)?.0;
    Some(unescape_xml(value))
}

fn unescape_xml(value: &str) -> String {
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

/// Splits a Windows command line the way `CommandLineToArgvW` does.
fn split(line: &str) -> Vec<String> {
    let mut arguments = Vec::new();
    let mut current = String::new();
    let mut started = false;
    let mut quoted = false;
    let mut backslashes = 0usize;

    for ch in line.chars() {
        match ch {
            '\\' => {
                backslashes += 1;
                started = true;
            }
            '"' => {
                // A run of backslashes before a quote is halved; an odd count
                // means the quote itself was escaped.
                for _ in 0..backslashes / 2 {
                    current.push('\\');
                }
                if backslashes % 2 == 1 {
                    current.push('"');
                } else {
                    quoted = !quoted;
                }
                backslashes = 0;
                started = true;
            }
            ch => {
                for _ in 0..backslashes {
                    current.push('\\');
                }
                backslashes = 0;
                if ch.is_whitespace() && !quoted {
                    if started {
                        arguments.push(core::mem::take(&mut current));
                        started = false;
                    }
                } else {
                    current.push(ch);
                    started = true;
                }
            }
        }
    }
    for _ in 0..backslashes {
        current.push('\\');
    }
    if started {
        arguments.push(current);
    }
    arguments
}

#[cfg(test)]
mod tests {
    use super::super::spec::{port_in, vault_in};
    use super::*;
    use std::path::PathBuf;

    const AWKWARD: &[&str] = &[
        r"C:\Users\user\Vault",
        r"C:\Users\A B\My Bookmarks",
        r"C:\Users\user\Zakładki",
        r"C:\Users\user\书签 📚",
        r"C:\Users\user\a&b",
        r"C:\Users\user\Vault\",
        r"C:\Users\user\100% done",
        "C:\\Users\\user\\say \"hi\"",
    ];

    /// Built unchecked so that Windows paths can be exercised from any host —
    /// `Path::is_absolute` answers for the platform the test runs on.
    fn spec_for(vault: &str) -> ServiceSpec {
        ServiceSpec::unchecked(r"C:\Program Files\bbb\bbb.exe", vault)
    }

    #[test]
    fn a_generated_task_round_trips_every_awkward_path() {
        for vault in AWKWARD {
            let spec = spec_for(vault).with_port(47321).expect("valid port");
            let text = task(&spec);
            let parsed = command_line(&text).expect("an Exec action");

            assert_eq!(parsed, spec.command_line(), "round trip for {vault}");
            assert_eq!(vault_in(&parsed), Some(PathBuf::from(vault)));
            assert_eq!(port_in(&parsed), Some(47321));
        }
    }

    #[test]
    fn a_trailing_backslash_does_not_swallow_the_rest_of_the_line() {
        // The classic Windows quoting bug: `"C:\Vault\"` ends with an escaped
        // quote, so `--bind` would become part of the vault path.
        let spec = spec_for(r"C:\Users\user\Vault\");
        let parsed = command_line(&task(&spec)).expect("Exec");

        assert_eq!(
            vault_in(&parsed),
            Some(PathBuf::from(r"C:\Users\user\Vault\"))
        );
        assert!(parsed.contains(&"--bind".to_owned()), "{parsed:?}");
        assert!(parsed.contains(&"127.0.0.1".to_owned()), "{parsed:?}");
    }

    #[test]
    fn the_task_triggers_at_logon_without_administrator_rights() {
        let text = task(&spec_for(r"C:\Users\user\Vault"));

        assert!(text.contains("<LogonTrigger>"), "{text}");
        assert!(text.contains("LeastPrivilege"), "{text}");
        assert!(text.contains("<RestartOnFailure>"), "{text}");
        assert!(text.contains("IgnoreNew"), "{text}");
    }

    #[test]
    fn the_definition_is_encoded_as_the_utf16_schtasks_requires() {
        let bytes = utf16le_bytes(task(&spec_for(r"C:\Users\user\书签")).as_str());

        assert_eq!(&bytes[..2], &[0xFF, 0xFE], "a UTF-16LE byte-order mark");
        // Declared and actual encoding agree, which is what `schtasks` checks.
        let decoded: Vec<u16> = bytes[2..]
            .chunks_exact(2)
            .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
            .collect();
        let text = String::from_utf16(&decoded).expect("valid UTF-16");
        assert!(text.contains("encoding=\"UTF-16\""), "{text}");
        assert!(text.contains("书签"), "{text}");
    }

    #[test]
    fn a_task_without_an_exec_action_yields_nothing() {
        assert_eq!(command_line("<Task><Settings/></Task>"), None);
    }
}
