//! The XDG autostart entry: the Linux fallback when systemd is not there.
//!
//! A desktop entry in `~/.config/autostart` is started once, at login, by the
//! desktop session — there is no supervision and therefore no restart on
//! failure. That is strictly worse than a systemd user unit, which is why it
//! is the fallback rather than the default, and why `bbb service status` has
//! to report it as the weaker thing it is instead of claiming a service is
//! being kept alive.

use super::quote::desktop_argument;
use super::spec::{SERVICE_DESCRIPTION, ServiceSpec};

/// The file name of the generated autostart entry.
pub(crate) const DESKTOP_FILE: &str = "bbb.desktop";

/// Renders the autostart desktop entry for `spec`.
pub(crate) fn desktop_entry(spec: &ServiceSpec) -> String {
    let exec = spec
        .command_line()
        .iter()
        .map(|argument| desktop_argument(argument))
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        "# Generated by `bbb service install`. Edits are replaced on the next install.\n\
         [Desktop Entry]\n\
         Type=Application\n\
         Version=1.0\n\
         Name={SERVICE_DESCRIPTION}\n\
         Comment=Serves a Markdown bookmark vault on loopback\n\
         Exec={exec}\n\
         Terminal=false\n\
         NoDisplay=true\n\
         X-GNOME-Autostart-enabled=true\n"
    )
}

/// Recovers the command line from an autostart entry, if it has an `Exec=`.
pub(crate) fn command_line(entry: &str) -> Option<Vec<String>> {
    let value = entry
        .lines()
        .map(str::trim)
        .find_map(|line| line.strip_prefix("Exec="))?;
    Some(split(&unescape_desktop_string(value)))
}

/// Undoes the desktop-entry *string* encoding, the outer of the two layers.
fn unescape_desktop_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let mut chars = value.chars();
    while let Some(ch) = chars.next() {
        if ch != '\\' {
            out.push(ch);
            continue;
        }
        match chars.next() {
            Some('s') => out.push(' '),
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some(other) => out.push(other),
            None => out.push('\\'),
        }
    }
    out
}

/// Splits the command line, the inner of the two layers.
///
/// `%%` is undone last, mirroring `systemd::split`: an escaped percent must
/// not be mistaken for a field code on the way back in either.
fn split(line: &str) -> Vec<String> {
    let mut arguments = Vec::new();
    let mut current = String::new();
    let mut started = false;
    let mut quoted = false;
    let mut chars = line.chars();

    while let Some(ch) = chars.next() {
        match ch {
            '\\' if quoted => {
                started = true;
                if let Some(escaped) = chars.next() {
                    current.push(escaped);
                }
            }
            '"' => {
                started = true;
                quoted = !quoted;
            }
            ch if ch.is_whitespace() && !quoted => {
                if started {
                    arguments.push(core::mem::take(&mut current));
                    started = false;
                }
            }
            ch => {
                started = true;
                current.push(ch);
            }
        }
    }
    if started {
        arguments.push(current);
    }

    arguments
        .into_iter()
        .map(|argument| argument.replace("%%", "%"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::super::spec::{port_in, vault_in};
    use super::*;
    use std::path::PathBuf;

    const AWKWARD: &[&str] = &[
        "/home/user/Vault",
        "/home/user/My Bookmarks",
        "/home/user/Zakładki",
        "/home/user/书签 📚",
        "/home/user/100% done",
        "/home/user/%f files",
        "/home/user/say \"hi\"",
        "/home/user/back\\slash",
        "/home/user/$HOME literal",
        "/home/user/it's mine",
    ];

    /// Expands field codes the way a desktop session does before it splits the
    /// line into arguments: `%%` is one literal percent, and every other `%X`
    /// is a code that expands to nothing here (there are no files or URIs to
    /// substitute, and an autostart entry names none).
    ///
    /// This runs over the *unescaped* `Exec` value, ignores quoting entirely,
    /// and happens before any word splitting — which is exactly why quoting a
    /// path is not enough to protect a `%` inside it.
    fn expand_field_codes(value: &str) -> String {
        let mut out = String::with_capacity(value.len());
        let mut chars = value.chars().peekable();
        while let Some(ch) = chars.next() {
            if ch != '%' {
                out.push(ch);
                continue;
            }
            match chars.next() {
                // A trailing `%` has no code to introduce, so it stays put.
                Some('%') | None => out.push('%'),
                // Any other code expands to nothing, taking its marker with it.
                Some(_) => {}
            }
        }
        out
    }

    #[test]
    fn a_generated_entry_round_trips_every_awkward_path() {
        for vault in AWKWARD {
            let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", vault)
                .with_port(47321)
                .expect("valid port");
            let text = desktop_entry(&spec);
            let parsed = command_line(&text).expect("the entry has an Exec");

            assert_eq!(parsed, spec.command_line(), "round trip for {vault}");
            assert_eq!(vault_in(&parsed), Some(PathBuf::from(vault)));
            assert_eq!(port_in(&parsed), Some(47321));
        }
    }

    #[test]
    fn the_entry_is_hidden_and_binds_loopback() {
        let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", "/home/user/Vault");
        let text = desktop_entry(&spec);

        assert!(text.contains("NoDisplay=true"), "{text}");
        assert!(text.contains("Terminal=false"), "{text}");
        let parsed = command_line(&text).expect("Exec");
        assert!(parsed.contains(&"127.0.0.1".to_owned()), "{parsed:?}");
    }

    #[test]
    fn a_dollar_sign_cannot_become_an_expansion() {
        let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", "/home/user/$HOME literal");
        let text = desktop_entry(&spec);
        // Escaped in the file...
        assert!(text.contains("\\\\$HOME"), "{text}");
        // ...and literal again once read back.
        assert_eq!(
            vault_in(&command_line(&text).expect("Exec")),
            Some(PathBuf::from("/home/user/$HOME literal"))
        );
    }

    /// The failure this guards against is not a parse error anyone sees: the
    /// session starts the daemon on a path that is *almost* the one the user
    /// chose, and the daemon refuses a directory that was never a vault.
    #[test]
    fn a_percent_in_a_path_cannot_become_a_field_code() {
        for vault in ["/home/user/100% done", "/home/user/%f files"] {
            let spec = ServiceSpec::unchecked("/usr/local/bin/bbb", vault);
            let text = desktop_entry(&spec);

            // Doubled in the file, exactly as systemd's generator does it:
            // every `%` in the value appears as an even-length run.
            let exec = text
                .lines()
                .find_map(|line| line.strip_prefix("Exec="))
                .expect("the entry has an Exec");
            assert!(
                exec.contains(&vault.replace('%', "%%")),
                "a bare percent survived: {exec}"
            );

            // And the path is intact after the expansion a desktop session
            // performs before it splits the line into arguments.
            let expanded = expand_field_codes(&unescape_desktop_string(exec));
            assert_eq!(
                vault_in(&split(&expanded)),
                Some(PathBuf::from(vault)),
                "field-code expansion mangled {vault}"
            );
        }
    }

    #[test]
    fn an_entry_without_an_exec_yields_nothing() {
        assert_eq!(command_line("[Desktop Entry]\nType=Application\n"), None);
    }
}
