//! The systemd **user** unit, and reading one back.
//!
//! A user unit needs no administrator: it lives under the user's own config
//! directory, `systemctl --user` manages it, and it runs as them. That is the
//! whole reason it is the first choice on Linux — installing a daemon must not
//! require a password prompt for something that only ever touches one person's
//! files.

use super::quote::systemd_argument;
use super::spec::{SERVICE_DESCRIPTION, ServiceSpec};

/// The file name of the generated unit.
pub(crate) const UNIT_FILE: &str = "bookmarks-but-better.service";

/// Renders the unit file for `spec`.
///
/// `Restart=on-failure` rather than `always`: a clean exit is the daemon being
/// asked to stop, and restarting it then would make `bookmarks-but-better service stop` a fight
/// rather than a command. `RestartSec` leaves room for a vault lock held by a
/// dying predecessor to be released before the replacement claims it.
pub(crate) fn unit(spec: &ServiceSpec) -> String {
    let exec_start = spec
        .command_line()
        .iter()
        .map(|argument| systemd_argument(argument))
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        "# Generated by `bookmarks-but-better service install`. Edits are replaced on the next install.\n\
         [Unit]\n\
         Description={SERVICE_DESCRIPTION}\n\
         Documentation=https://github.com/farhadeidi/bookmarks-but-better\n\
         After=default.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={exec_start}\n\
         Restart=on-failure\n\
         RestartSec=5\n\
         # Counts, identities, codes and paths only: no bookmark titles or URLs\n\
         # are ever logged, at any level.\n\
         Environment=BOOKMARKS_BUT_BETTER_LOG=info\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

/// Recovers the command line from a unit file, if it has an `ExecStart=`.
///
/// Used on upgrade to read back what the previous install actually runs, so a
/// port the user configured is preserved rather than overwritten by whatever
/// the new default happens to be.
pub(crate) fn command_line(unit: &str) -> Option<Vec<String>> {
    let line = unit
        .lines()
        .map(str::trim)
        .find_map(|line| line.strip_prefix("ExecStart="))?;
    Some(split(line))
}

/// Splits an `ExecStart=` value the way systemd does.
///
/// Whitespace separates; a double-quoted run is one argument; a backslash
/// escapes the next character inside or outside quotes; and `%%` is an escaped
/// literal `%`, undone last so that an escaped percent cannot be mistaken for
/// a specifier here either.
fn split(line: &str) -> Vec<String> {
    let mut arguments = Vec::new();
    let mut current = String::new();
    let mut started = false;
    let mut quoted = false;
    let mut chars = line.chars();

    while let Some(ch) = chars.next() {
        match ch {
            '\\' => {
                started = true;
                if let Some(escaped) = chars.next() {
                    current.push(escaped);
                }
            }
            '"' => {
                started = true;
                quoted = !quoted;
            }
            ch if ch.is_whitespace() && !quoted => {
                if started {
                    arguments.push(core::mem::take(&mut current));
                    started = false;
                }
            }
            ch => {
                started = true;
                current.push(ch);
            }
        }
    }
    if started {
        arguments.push(current);
    }

    arguments
        .into_iter()
        .map(|argument| argument.replace("%%", "%"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::super::spec::{port_in, vault_in};
    use super::*;
    use std::path::PathBuf;

    fn spec_for(vault: &str) -> ServiceSpec {
        ServiceSpec::unchecked("/usr/local/bin/bookmarks-but-better", vault)
    }

    #[test]
    fn the_unit_binds_loopback_and_restarts_only_on_failure() {
        let text = unit(&spec_for("/home/user/Vault"));

        assert!(text.contains("--bind\" \"127.0.0.1"), "{text}");
        assert!(text.contains("Restart=on-failure"), "{text}");
        // `always` would make a deliberate stop into a restart loop.
        assert!(!text.contains("Restart=always"), "{text}");
        assert!(text.contains("WantedBy=default.target"), "{text}");
    }

    #[test]
    fn the_unit_carries_only_a_command_line_and_a_log_level() {
        // A definition is a command line plus a log level. It has no field a
        // bookmark title or URL could occupy, and the level it pins is the one
        // the daemon emits counts, identities, codes and paths under — never
        // titles or URLs, at any level.
        let text = unit(&spec_for("/home/user/Vault"));
        assert!(text.contains("BOOKMARKS_BUT_BETTER_LOG=info"), "{text}");
        assert!(!text.contains("debug"), "{text}");
        assert!(!text.contains("trace"), "{text}");

        // The only URL in the file is this project's own documentation link.
        let urls: Vec<&str> = text
            .lines()
            .filter(|line| line.contains("://"))
            .filter(|line| !line.starts_with("Documentation="))
            .collect();
        assert!(urls.is_empty(), "unexpected URL in the unit: {urls:?}");
    }

    /// The paths a user actually has. Each must survive generation *and* the
    /// read-back an upgrade depends on.
    const AWKWARD: &[&str] = &[
        "/home/user/Vault",
        "/home/user/My Bookmarks",
        "/home/user/Zakładki",
        "/home/user/书签 📚",
        "/home/user/100% done",
        "/home/user/say \"hi\"",
        "/home/user/back\\slash",
        "/home/user/it's mine",
    ];

    #[test]
    fn a_generated_unit_round_trips_every_awkward_path() {
        for vault in AWKWARD {
            let spec = spec_for(vault).with_port(47321).expect("valid port");
            let text = unit(&spec);
            let parsed = command_line(&text).expect("the unit has an ExecStart");

            assert_eq!(parsed, spec.command_line(), "round trip for {vault}");
            assert_eq!(
                vault_in(&parsed),
                Some(PathBuf::from(vault)),
                "vault recovered for {vault}"
            );
            assert_eq!(port_in(&parsed), Some(47321));
        }
    }

    #[test]
    fn a_percent_in_a_path_is_escaped_so_systemd_cannot_expand_it() {
        let text = unit(&spec_for("/home/user/100% done"));
        assert!(text.contains("100%% done"), "{text}");
        // And it comes back as one percent, not two.
        let parsed = command_line(&text).expect("ExecStart");
        assert_eq!(
            vault_in(&parsed),
            Some(PathBuf::from("/home/user/100% done"))
        );
    }

    #[test]
    fn a_path_with_a_space_stays_a_single_argument() {
        let parsed = command_line(&unit(&spec_for("/home/user/My Bookmarks"))).expect("ExecStart");
        assert!(
            parsed.contains(&"/home/user/My Bookmarks".to_owned()),
            "{parsed:?}"
        );
    }

    #[test]
    fn a_unit_without_an_exec_start_yields_nothing() {
        assert_eq!(command_line("[Unit]\nDescription=x\n"), None);
    }

    #[test]
    fn a_hand_edited_port_is_what_is_read_back() {
        // Preservation has to follow the file, not a marker we wrote: a user
        // who edited the unit chose that port.
        let text = unit(&spec_for("/home/user/Vault")).replace("\"52222\"", "\"40404\"");
        let parsed = command_line(&text).expect("ExecStart");
        assert_eq!(port_in(&parsed), Some(40404));
    }

    #[test]
    fn an_unquoted_exec_start_still_parses() {
        // Not a shape this generator emits, but one a user may have written.
        let parsed = command_line(
            "ExecStart=/usr/local/bin/bookmarks-but-better serve --vault /tmp/v --port 12345\n",
        )
        .expect("ExecStart");
        assert_eq!(port_in(&parsed), Some(12345));
        assert_eq!(vault_in(&parsed), Some(PathBuf::from("/tmp/v")));
    }
}
